#!/bin/bash

READLINK="$(which greadlink 2>/dev/null || which readlink)"
SCHEMAVIEW_PATH="$(dirname "$("$READLINK" -f "$0")")"

exec $SCHEMAVIEW_PATH/node_modules/.bin/electron $SCHEMAVIEW_PATH/main.js "$@"
